<a href="https://colab.research.google.com/github/adityayadav4507/100Days_of_ML/blob/main/50_Day_C_multiple_LR_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
import numpy as np
from sklearn.datasets import load_diabetes

In [137]:
X,y=load_diabetes(return_X_y=True)

In [138]:
X.shape

(442, 10)

In [139]:
y.shape

(442,)

In [140]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

# Using SkLearn Linear Regression

In [141]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [142]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [143]:
lr.fit(X_train,y_train)

LinearRegression()

In [144]:
y_pred=lr.predict(X_test)

In [145]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print("sklearn r2 =",r2)

sklearn r2 = 0.4399338661568968


In [146]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [147]:
lr.intercept_

np.float64(151.88331005254167)

# make our own class of LR

In [148]:
class meraLR():
    def __init__(self):
      self.coef_=None
      self.intercept_=None

    def fit(self,X_train,y_train):
      if X_train.ndim==1:
        X_train=X_train.values.reshape(-1,1)
      X_train=np.insert(X_train,0,1,axis=1)
      beta=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
      self.intercept_=beta[0]
      self.coef_=beta[1:] # bec array h

    def pred(self,X_test):
      if X_test.ndim==1:
        X_test=X_test.values.reshape(-1,1)
      return np.dot(X_test,self.coef_)+self.intercept_

In [149]:
  X_train


array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [150]:
 np.insert(X_train,0,1,axis=1) # add 1 in 0th colummn

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [151]:
lr_=meraLR() # make object of class

In [152]:
lr_.fit(X_train,y_train)

In [153]:
y_pred=lr_.pred(X_test)

In [154]:
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [155]:
r2_mera=r2_score(y_test,y_pred)
print("mera r2 =",r2_mera)
print("sk learn r2 =",r2)

mera r2 = 0.43993386615689634
sk learn r2 = 0.4399338661568968


In [156]:
print("mera coeff =",lr_.coef_)
print("sk learn coeff =",lr.coef_)

mera coeff = [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
sk learn coeff = [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]


In [157]:
print("mera intercept =",lr_.intercept_)
print("sk learn intercept =",lr.intercept_)

mera intercept = 151.88331005254165
sk learn intercept = 151.88331005254167


# run the same class for simple LR

In [158]:
import pandas as pd
df=pd.read_csv('/content/weight-height.csv')

In [159]:
df=df.drop(columns='Gender', axis=1)

In [160]:
df.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [161]:
X=df.iloc[:,0]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [162]:
X_train.shape # it become sequence 1D aray meraLR-> fit function -> insert 1 -> when there is column . in this array no column

(8000,)

In [163]:
X_train

8856    64.875127
1545    63.183641
8136    65.604100
7768    62.180780
7782    63.217278
          ...    
1099    71.423946
2514    70.704094
6637    62.893822
2575    68.411275
7336    62.369296
Name: Height, Length: 8000, dtype: float64

In [164]:
X_train.values.reshape(-1,1) # .values-> convert pd into np bec pd do not have reshape function
# -1 = row -> tell the numpy that all values in 1D array is are row
# 1 = col -> tell the numpy that there is 1 column in the data

array([[64.87512711],
       [63.18364112],
       [65.60410039],
       ...,
       [62.8938216 ],
       [68.41127477],
       [62.36929577]])

In [165]:
X_train.values.reshape(-1,1).shape

(8000, 1)

In [166]:
X

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...    
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [167]:
simple_lr=meraLR()
simple_lr.fit(X_train,y_train)

In [168]:
y_pred_simple=simple_lr.pred(X_test)

In [169]:
y_pred_simple

array([120.54965323, 135.55036464, 192.58077136, ..., 145.67967351,
       194.9370124 , 184.50151637])

In [174]:
r2_score(y_test,y_pred_simple) # same as we make Simple regression class

0.8562263885800667