<a href="https://colab.research.google.com/github/adityayadav4507/100Days_of_ML/blob/main/52_Day_stochastic_GD_From_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [186]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import numpy as np
import pandas as pd

In [187]:
X,y=load_diabetes(return_X_y=True)

In [188]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2 , random_state=22)

In [189]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [190]:
from sklearn.metrics import r2_score
y_pred=lr.predict(X_test)
r2=r2_score(y_test,y_pred)
r2

0.48002331551397015

In [191]:
c=lr.intercept_

In [192]:
X_train[10]

array([-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
       -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284])

In [193]:
y_train[3].flatten().shape

(1,)

# Make class

In [194]:
class SGD:

  def __init__ (self,learning_rate=0.01,epochs=100):
    self.lr=learning_rate
    self.epochs=epochs
    self.coef_=None
    self.intercept_=None

  def fit(self,X_train,y_train):
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1]) # no. of col = no. of coeff

    for i in range(self.epochs):

      for j in range(X_train.shape[0]):


         select_row=np.random.randint(0,X_train.shape[0],size=1) # select random row from 0 to n-1

         slope= -2*(y_train[select_row] - np.dot(X_train[select_row],self.coef_) -self.intercept_).flatten().dot(X_train[select_row])
         self.coef_ =self.coef_ - self.lr*slope

         slope1= -2*(y_train[select_row] - np.dot(X_train[select_row],self.coef_) -self.intercept_)
         self.intercept_ = self.intercept_ - self.lr*slope1

    print(self.coef_,self.intercept_)


  def predict(self,X_test):
    return np.dot(X_test,self.coef_)+self.intercept_

In [195]:
np.random.randint(y_train.min(),y_train.max(),size=y_train.shape[0]) # its not pick the random y_train its pick the value betwnn min and max of y_train

array([263, 293,  37,  64, 205, 303, 148, 317,  86, 209, 308, 238, 224,
       333,  51, 108,  72, 324,  96, 213,  66,  78, 266, 198, 125, 316,
       323, 339, 221, 286, 185,  31, 170, 222, 338, 114, 187, 180, 128,
       182, 318, 296, 206,  83, 158,  52, 168, 143, 109, 269, 142,  34,
       287, 168, 221, 337, 198, 278, 215,  27, 299, 304,  93, 341, 226,
        96, 235, 171, 241, 138, 186, 212,  82,  35, 138,  53, 189, 101,
       170,  25, 126, 269, 150, 321, 319, 289, 114, 186, 171, 304,  70,
       340, 332,  47, 245, 320, 268, 228,  27, 150,  25, 180,  81, 101,
        56,  71, 229,  30, 129, 132, 162, 143, 252,  96, 217, 227,  78,
       189, 186, 207, 318, 201,  35, 130,  48, 142, 119,  41, 275, 342,
       161,  43, 321, 180, 171, 124, 146,  30,  92, 187, 149, 103, 216,
       232, 184, 250, 292, 189, 307, 260, 136,  69, 106, 295, 254, 140,
       129, 112,  32,  36, 238, 300,  61, 323, 281, 274, 236, 108, 174,
       330, 273,  54, 318, 164, 139,  67, 266,  91, 216, 278, 25

In [196]:
np.random.randint(1,X_train.shape[0]+1,size=1)  # it select random row from 1 - n+1 , n+1 not inclusive

array([42])

In [197]:
y_train.shape

(353,)

In [198]:
np.random.randint(0,2,size=2) # size=2 give size of array of 2 in range of 0 to 5

array([0, 1])

In [199]:
np.random.randn(4) # range(-inf , + inf) normal dist mean=0 , std=1

array([ 1.01754119, -2.00741406, -0.26185026,  1.73922674])

In [200]:
np.random.random(4) # range(0-1) uniform distribution

array([0.6716554 , 0.87711401, 0.71020094, 0.68387427])

In [201]:
sdg=SGD(learning_rate=0.01,epochs=40)
sdg.fit(X_train,y_train)
sgd_r2=r2_score(y_test,sdg.predict(X_test))

[  61.89284247  -66.18744617  310.8907408   189.20805259   34.48067648
    1.39678209 -177.59908799  154.61383187  285.41699111  147.22108168] [154.5244696]


# apply sklearn SGD class

In [204]:
from sklearn.linear_model import SGDRegressor

l=SGDRegressor(max_iter=40,learning_rate='constant',eta0=0.01)
l.fit(X_train,y_train)
sk_r2=r2_score(y_test,l.predict(X_test))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1608: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


In [205]:
print("sgd class r2 =", sgd_r2)
print("sgd sklearn r2 =", sk_r2)

sgd class r2 = 0.42855657819348847
sgd sklearn r2 = 0.36533709636589773
