<a href="https://colab.research.google.com/github/adityayadav4507/100Days_of_ML/blob/main/64_Day_bagging_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification

In [2]:
X,y= make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [4]:
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
accuracy_score(y_test,y_pred)

0.84

# Bagging

In [5]:
from sklearn.ensemble import BaggingClassifier

bag=BaggingClassifier(
                      estimator=DecisionTreeClassifier(), # selcting DT as a base model
                      n_estimators=500, # selecting no. of base model
                      max_samples=0.25, # selecting no of rows
                      bootstrap=True,   # selcting rows with replacement
                      random_state=42)
bag.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.25,
                  n_estimators=500, random_state=42)

In [6]:
y_pred= bag.predict(X_test)
accuracy_score(y_test,y_pred)

0.865

In [7]:
bag.estimators_samples_ [0]# it give which row given to our model 1 , row no are written

array([475,  41, 332, 642, 231, 604, 711, 370, 632, 540, 745, 596,   6,
       324, 338, 307, 105, 586, 290, 260,   8, 398, 288, 510, 571, 607,
       505, 515, 150, 363, 116, 455, 194, 361, 437, 589, 184, 336, 754,
       753, 725,  64, 768, 378,  59, 615, 491, 337, 553, 437, 582, 132,
       256, 572, 791, 412, 526, 746, 249, 183, 203, 465, 340, 677, 100,
       685, 725,  23, 582,   1, 337, 172, 294, 353,  52, 521, 338, 327,
       109,  73, 447, 217, 196, 499,  14, 288, 616, 616, 557, 492, 565,
       773, 146,  36, 303, 791, 752,  39, 632, 292, 512, 470, 135, 254,
       634, 437, 781, 734, 265,  15, 703, 774, 333,  48,  27, 582, 476,
       316, 476, 404, 685,  49, 131, 268, 481,  85, 184, 303,  99, 375,
       401, 513, 602, 756, 739, 166, 763, 548, 598, 748, 576,  66, 723,
        68, 332, 599, 733, 605, 110,  79, 464, 577, 500, 208, 313, 711,
       587,   5, 710, 200, 358, 270,   1, 669,  26, 609, 272, 385, 751,
       224, 472, 322, 687, 763, 650, 245,  62, 121, 427,  11, 53

In [8]:
bag.estimators_samples_ [0].shape

(200,)

In [9]:
bag.estimators_features_[0] # how many columns given to our model 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Bagging Using SVM

In [10]:
from sklearn.svm import SVC

In [11]:
bag1= BaggingClassifier(
                         estimator=SVC(),
                         n_estimators=500,
                         max_samples=0.25,
                         bootstrap=True,
                         random_state=42
)
bag1.fit(X_train,y_train)

BaggingClassifier(estimator=SVC(), max_samples=0.25, n_estimators=500,
                  random_state=42)

In [12]:
y_pred=bag1.predict(X_test)
accuracy_score(y_test,y_pred)

0.83

# Pasting

In [13]:
bag2= BaggingClassifier(
                         estimator=DecisionTreeClassifier(),
                         n_estimators=500,
                         max_samples=0.25,
                         bootstrap=False,
                         random_state=42,
                         verbose=1,
                         n_jobs=-1
)
bag2.fit(X_train,y_train)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    7.4s finished


BaggingClassifier(bootstrap=False, estimator=DecisionTreeClassifier(),
                  max_samples=0.25, n_estimators=500, n_jobs=-1,
                  random_state=42, verbose=1)

In [14]:
y_pred=bag2.predict(X_test)
accuracy_score(y_test,y_pred) # bagging give better result bec randomness is high

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.4s finished


0.875

# Random SubSpaces

In [15]:
bag4= BaggingClassifier(
                         estimator=DecisionTreeClassifier(),
                         n_estimators=500,
                         max_samples=1.0,
                         bootstrap=False,
                         max_features=0.5,
                         bootstrap_features=True,
                         random_state=42,
                         verbose=1,
                         n_jobs=-1
)
bag4.fit(X_train,y_train)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    7.0s finished


BaggingClassifier(bootstrap=False, bootstrap_features=True,
                  estimator=DecisionTreeClassifier(), max_features=0.5,
                  n_estimators=500, n_jobs=-1, random_state=42, verbose=1)

In [16]:
y_pred= bag4.predict(X_test)
accuracy_score(y_test,y_pred)


[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.3s finished


0.875

In [17]:
bag4.estimators_samples_[0].shape

(800,)

In [18]:
bag4.estimators_features_[0]

array([9, 2, 9, 7, 7])

# Random Patches

In [19]:
bag5= BaggingClassifier(
                         estimator=DecisionTreeClassifier(),
                         n_estimators=500,
                         max_samples=.5,
                         bootstrap=False,
                         max_features=0.5,
                         bootstrap_features=False,
                         random_state=42,
                         verbose=1,
                         n_jobs=-1
)
bag5.fit(X_train,y_train)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    1.6s finished


BaggingClassifier(bootstrap=False, estimator=DecisionTreeClassifier(),
                  max_features=0.5, max_samples=0.5, n_estimators=500,
                  n_jobs=-1, random_state=42, verbose=1)

In [20]:
y_pred= bag5.predict(X_test)
accuracy_score(y_test,y_pred)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.2s finished


0.87

# OOB Score
out of bag samples.
when we randomley selects rows from the datasets multiple times some rows are lets in the datasets which not given to any model these values are OOB


```
# 37% rows are such rows in the datatsets statical
```



In [21]:
from sklearn.ensemble import BaggingClassifier

bag=BaggingClassifier(
                      estimator=DecisionTreeClassifier(), # selcting DT as a base model
                      n_estimators=500, # selecting no. of base model
                      max_samples=0.25, # selecting no of rows
                      bootstrap=True,   # selcting rows with replacement
                      oob_score=True,
                      random_state=42)
bag.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.25,
                  n_estimators=500, oob_score=True, random_state=42)

In [22]:
bag.oob_score_ # give prediction on not trained datasets

0.90375

In [23]:
y_pred= bag.predict(X_test)
accuracy_score(y_test,y_pred)

0.865

# GridSearchCV/ RandomSearchCV

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
from inspect import Parameter
parameters = {
    'n_estimators': [50,100,500],
    'max_samples': [0.1,0.4,0.7,1.0],
    'bootstrap' : [True,False],
    'max_features' : [0.2,0.3,0.5,0.6,0.7,1.0]
}

In [26]:
search = GridSearchCV(BaggingClassifier(),
                       parameters,
                       cv=3,
                       n_jobs=-1)

In [27]:
search.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=BaggingClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'max_features': [0.2, 0.3, 0.5, 0.6, 0.7, 1.0],
                         'max_samples': [0.1, 0.4, 0.7, 1.0],
                         'n_estimators': [50, 100, 500]})

In [28]:
y_pred=search.predict(X_test)
accuracy_score(y_test,y_pred)

0.885

In [29]:
search.best_params_

{'bootstrap': False,
 'max_features': 1.0,
 'max_samples': 0.7,
 'n_estimators': 100}

In [30]:
search.best_score_

np.float64(0.916237222269156)