<a href="https://colab.research.google.com/github/adityayadav4507/100Days_of_ML/blob/main/Day_29_without_pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [281]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [282]:
df = pd.read_csv('/content/titanic.csv')


In [283]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [284]:
# unnecessary column remove
df.drop(columns=['PassengerId','Name','Ticket','Cabin'] ,inplace=True)

In [285]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

# Step -1 -> Train test split

In [286]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2, # 20 data used in test
                                                random_state=42) # same spilt get when we run this code again and again


In [287]:
X_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [288]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [289]:
# Apply imputer
si_age = SimpleImputer() # by default mean mean is the strategy
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']]) # this is new array original df no changes
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [290]:
# Apply One Hot Encoding  on Sex and embarked  nominal category

ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore') # two different object of OHE bec of one have missing vale (embarked)
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked_ohe = ohe_embarked.fit_transform(X_train_embarked) # not using original column bec of missing value in original column

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked_ohe = ohe_embarked.transform(X_test_embarked)



In [291]:
X_test.head(2)

Pclass   Sex   Age  SibSp  Parch     Fare Embarked
709       3  male   NaN      1      1  15.2458        C
439       2  male  31.0      0      0  10.5000        S

In [292]:
# we have 3 new array
# make new array train rem
X_train_rem= X_train.drop(columns=['Sex','Age','Embarked'])
X_test_rem= X_test.drop(columns=['Sex','Age','Embarked'])



In [293]:
# combine new array (3) and x train rem column

X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_embarked_ohe,X_train_sex), axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_embarked_ohe,X_test_sex), axis=1)

In [294]:
X_test_transformed.shape

(179, 10)

In [295]:
# train model
clf= DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [296]:
y_pred=clf.predict(X_test_transformed)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1])

In [297]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.776536312849162

In [298]:
import pickle # to deploy our model on server web dev part

import os # for creating directory
os.makedirs('model',exist_ok=True)


In [299]:
pickle.dump(ohe_sex,open('model/ohe.sex.pkl' , 'wb'))
pickle.dump(ohe_embarked,open('model/ohe.embarked.pkl' , 'wb'))
pickle.dump(clf,open('model/clf.pkl','wb'))


# Step 2 - Deploy on web (this code is production code at web)

In [300]:
import pickle
import numpy as np

In [301]:
# open the binary file (decode)

ohe_sex=pickle.load(open('/content/model/ohe.sex.pkl','rb'))
ohe_embarked=pickle.load(open('/content/model/ohe.embarked.pkl','rb'))
clf=pickle.load(open('/content/model/clf.pkl','rb'))

In [302]:
#assume user input
# 	1.Pclass	2.Sex	3.Age	4.SibSp	5.Parch	6.Fare	7.Embarked

test_input=np.array([3,'male',22.0,1,0,7.2500,'S'],dtype=object).reshape(1,7)

In [303]:
test_input

array([[3, 'male', 22.0, 1, 0, 7.25, 'S']], dtype=object)

In [304]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [305]:
test_input_sex.shape

(1, 2)

In [306]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [307]:
test_input_embarked.shape

(1, 3)

In [308]:
test_input_age=test_input[:,2].reshape(1,1,)

In [309]:
test_input_age.shape

(1, 1)

In [310]:
test_input_rmed=test_input[:,[0,3,4,5]]

In [311]:
test_input_rmed.shape

(1, 4)

In [312]:
rmed=np.concatenate((test_input_rmed,test_input_age,test_input_embarked,test_input_sex
                     ),axis=1) # maintain the order

In [313]:
rmed.shape

(1, 10)

In [314]:
clf.predict(rmed)

array([0])